import{a as y,S as q,i}from"./assets/vendor-DA0uMjGz.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(o){if(o.ep)return;o.ep=!0;const a=s(o);fetch(o.href,a)}})();const S="32386885-8dbf1bc36075d10a6eaf5580b";y.defaults.baseURL="https://pixabay.com/api/";async function f(e,r=1){return(await y.get("",{params:{key:S,q:`${e}`,image_type:"photo",page:r,per_page:15}})).data}let d=null;function h(e,r){const s=e.map(({webformatURL:n,largeImageURL:o,tags:a,likes:l,views:w,comments:v,downloads:M})=>`
        <li class='gallery-img-item'>
        <div class="box-img">
         <a href='${o}'>
          <img src="${n}" alt="${a} "/>
         </a>
        </div>
     
        <div class='gallery-wrapper-text'>
          <p class='gallery-img-text'>Likes <span class='gallery-span'>${l}</span></p>
          <p class='gallery-img-text'>Views<span class='gallery-span'>${w}</span></p>
          <p class='gallery-img-text'>Comments<span class='gallery-span'>${v}</span></p>
          <p class='gallery-img-text'>Downloads<span class='gallery-span'>${M}</span></p>
        </div>
      </li>
    `).join("");r.insertAdjacentHTML("beforeend",s),d?d.refresh():d=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function x(e){e.innerHTML=""}function b(e){e.classList.remove("hidden")}function u(e){e.classList.add("hidden")}function $(e){e.classList.remove("hidden-btn")}function g(e){e.classList.add("hidden-btn")}const L=e=>{e.disabled=!0},m=e=>{e.disabled=!1},P=e=>{window.scrollBy({top:e*2,behavior:"smooth"})},t={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader-gallery"),button:document.querySelector(".form-btn"),buttonLoadMore:document.querySelector("#load-more")};let c=1,p="";t.form.addEventListener("submit",async e=>{e.preventDefault();const r=e.target.elements.search.value.trim();if(p=r,x(t.gallery),c=1,!p){u(t.loader),g(t.buttonLoadMore),m(t.button),i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:"Sorry, there are no images matching </br> your search query. Please try again!"});return}g(t.buttonLoadMore),b(t.loader),L(t.button);try{const{hits:s}=await f(r,c);if(s.length===0){i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:"Sorry, there are no images matching </br> your search query. Please try again!"});return}h(s,t.gallery),$(t.buttonLoadMore)}catch(s){i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:`${s.message}`})}finally{u(t.loader),m(t.button)}});t.buttonLoadMore.addEventListener("click",async()=>{L(t.buttonLoadMore),c+=1;try{const{totalHits:e,hits:r}=await f(p,c),s=Math.ceil(e/r.length);if(c>=s){i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:"Sorry, there are no images matching </br> your search query. Please try again!"}),g(t.buttonLoadMore);return}h(r,t.gallery),b(t.loader);const n=document.querySelector(".gallery-img-item");if(n){const{height:o}=n.getBoundingClientRect();P(o)}}catch(e){g(t.buttonLoadMore),i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:`${e.message}`})}finally{m(t.buttonLoadMore),u(t.loader)}});
//# sourceMappingURL=index.js.map
