import{a as y,S as M,i}from"./assets/vendor-DA0uMjGz.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function c(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const S="32386885-8dbf1bc36075d10a6eaf5580b";y.defaults.baseURL="https://pixabay.com/api/";async function f(e,o=1){return(await y.get("",{params:{key:S,q:`${e}`,image_type:"photo",page:o,per_page:15}})).data}let g=null;function h(e,o){const s=e.map(({webformatURL:c,largeImageURL:t,tags:a,likes:n,views:w,comments:v,downloads:q})=>`
        <li class='gallery-img-item'>
        <div class="box-img">
         <a href='${t}'>
          <img src="${c}" alt="${a} "/>
         </a>
        </div>
     
        <div class='gallery-wrapper-text'>
          <p class='gallery-img-text'>Likes <span class='gallery-span'>${n}</span></p>
          <p class='gallery-img-text'>Views<span class='gallery-span'>${w}</span></p>
          <p class='gallery-img-text'>Comments<span class='gallery-span'>${v}</span></p>
          <p class='gallery-img-text'>Downloads<span class='gallery-span'>${q}</span></p>
        </div>
      </li>
    `).join("");o.insertAdjacentHTML("beforeend",s),g?g.refresh():g=new M(".gallery a",{captionsData:"alt",captionDelay:250})}function x(e){e.innerHTML=""}function b(e){e.classList.remove("hidden")}function d(e){e.classList.add("hidden")}function $(e){e.classList.remove("hidden-btn")}function u(e){e.classList.add("hidden-btn")}const L=e=>{e.disabled=!0},m=e=>{e.disabled=!1},P=e=>{window.scrollBy({top:e*2,behavior:"smooth"})},r={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader-gallery"),button:document.querySelector(".form-btn"),buttonLoadMore:document.querySelector("#load-more")};let l=1,p="";r.form.addEventListener("submit",async e=>{e.preventDefault();const o=e.target.elements.search.value.trim();if(p=o,x(r.gallery),l=1,!p){d(r.loader),u(r.buttonLoadMore),m(r.button),i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:"Sorry, there are no images matching </br> your search query. Please try again!"});return}u(r.buttonLoadMore),b(r.loader),L(r.button);try{const{hits:s}=await f(o,l);if(s.length===0){i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:"Sorry, there are no images matching </br> your search query. Please try again!"});return}h(s,r.gallery),$(r.buttonLoadMore)}catch(s){i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:`${s.message}`})}finally{d(r.loader),m(r.button)}});r.buttonLoadMore.addEventListener("click",async()=>{l+=1,L(r.buttonLoadMore),b(r.loader);try{const e=await f(p,l);if(l>=e.totalHits){i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:"Sorry, there are no images matching </br> your search query. Please try again!"}),u(r.buttonLoadMore);return}h(e.hits,r.gallery);const o=document.querySelector(".gallery-img-item");if(o){const{height:s}=o.getBoundingClientRect();P(s)}}catch(e){i.show({position:"topRight",iconUrl:"./img/Group (1).svg",messageColor:"rgba(255, 255, 255, 1)",color:"rgba(239, 64, 64, 1)",message:`${e.message}`})}finally{m(r.buttonLoadMore),d(r.loader)}});
//# sourceMappingURL=index.js.map
